### ISSUE TITLE
Does not work with my IIS Server

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [hpoul/ntlm_dio#1]
Hi hpoul,
Thanks for your project. It give me the hope to talk with IIS using ntlm.
- It does not work with my server. My server info
```
content-type: text/html; charset=us-ascii
server: Microsoft-HTTPAPI/2.0
```
- Does CookieManager is required for NTLM Auth?
- I read your codes, Does `ntlm_dio` only support HTTP GET method?

**Comment by hpoul** [comment]
Basically yes, CookieManager is pretty much required, otherwise every request would need a new authentication flow..

this authentication flow would need to be a get request right now, yes..

**Comment by jinaiyuanbaojie** [comment]
Thanks for your reply.  Got it!
Your codes work well now. 
I set up a break point so the connection close:( My mistake

**Comment by jinaiyuanbaojie** [comment]
@hpoul You use `dio.fetch` api to replace dio.get. Then your project will support POST request.
https://github.com/hpoul/ntlm_dio/blob/379f5d819b52ad7cbfd4cf4a27abbf5a7f5dfbd8/lib/src/dio_interceptor.dart#L83

**Comment by jinaiyuanbaojie** [comment]
@hpoul Thanks for your help, you can close this issue now. :)

**Comment by jinaiyuanbaojie** [comment]
> Basically yes, CookieManager is pretty much required, otherwise every request would need a new authentication flow..
> 
> this authentication flow would need to be a get request right now, yes..
